### ISSUE TITLE
question for "FAVAR - BBE(2005) Replication in R"

### ISSUE THREAD

**Issue by Beckybs** [jbduarte/blog#3]
Hello, I read your "FAVAR - BBE(2005) Replication in R". 
And I wonder the data named "bbe_data.xlsx" is collected by yourself or from other place?
I want to redo this in R, so have to check my data is the same with yours.
Thank you!

**Comment by jbduarte** [comment]
Hi!

The data I used is the original data of the BBE(2005) paper.

Here it is:

**Comment by Beckybs** [comment]
so you mean you downloaded the data on the same website as the author?
"DRI/McGraw Hill Basic Economics Database" mentioned by the author.

**Comment by jbduarte** [comment]
I downloaded it from the paper replication files.

To download data, you need to download each series in BLS and FRED.

But I suggest you use this database that is always updated: 

https://research.stlouisfed.org/econ/mccracken/fred-databases/ <https://research.stlouisfed.org/econ/mccracken/fred-databases/>

Best,

J

**Comment by Beckybs** [comment]
Thank you!
